### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by mathstuf** [Kitware/MetaIO#36]
Is ITK ready if I make a PR which adds `override` to the headers or does it need to be conditionalized?

Cc: @thewtex

**Comment by jcfr** [comment]
My understanding is that C++11 is currently optional for ITK and should probably stay optional until python 2.7 reaches end of life (or until ITK decides to stop providing wheels for python 2.7)

Otherwise, from Slicer perspective, the build system has been updated to work with c++11 and VTK8. The next release (in few weeks) will be the last with VTK7 and without c++ 11 support. Then it will become mandatory.

**Comment by mathstuf** [comment]
What does Python 2.7 have to do with it?

**Comment by jcfr** [comment]
Since the compiler used to generate python 2.7 wheel doesn't support C++11, the time being ITK needs to build without C++11. 

This means the support of C++11 in MetaIO would need to be conditionalized.

**Comment by mathstuf** [comment]
Oh…we use VS2013 to make Python modules here, but we're also not making official wheels, but just binaries.

**Comment by jcfr** [comment]
If you build both the python interpreter and the wheels, you can definitively use a compiler that support c++ 11.

Since ITK provides wheels ABI compatible with the official py2.7 distribution, it still need to support building without c++11. Indeed, the compiler used is `Microsoft Visual C++ Compiler for Python 2.7` (or VS2008) and it doesn't support c++11. More details, see http://scikit-build.readthedocs.io/en/latest/generators.html#windows

**Comment by mathstuf** [comment]
FYI, we build Python with 2008 and ParaView with 2013 just fine. C ABIs don't need to share a compiler.

**Comment by jcfr** [comment]
That is neat.

To make sure I understand ... Are you saying that python binary wheels for python 2.7 can be compiled with any version of Microsoft compiler and assuming the wheel is properly named, it will just work ? 


I also wonder how we can deal with the runtime installation ? (statically compiling the runtime into the libraries, installing it within the wheels, using assembly....) 

While your suggestion can work on a specific machine,  I am not sure we can generalize.

**Comment by mathstuf** [comment]
We do this for ParaView binaries. The issue comes up when you have two C++ libraries talking to each other via a C++ interface. *Those* need to agree on compilers. For example, if you have `hdf5.dll` coming from `h5py` in a wheel and you try to use *that* HDF5 library, you have to agree. However, VTK mangles its HDF5 library name and symbols, so it's fine.

**Comment by mathstuf** [comment]
There are issues in C ABIs where one library calls `malloc` and another calls `free` on that memory. Those need to share a compiler (more specifically, runtime) as well.

**Comment by jcfr** [comment]
Makes sense, basically calls should not go beyond runtime DLL boundary. 

For ITK, we definitively played it safe and use a matching compiler. I anticipate we would have trouble with the [ITKBridgeNumPy](https://github.com/InsightSoftwareConsortium/ITKBridgeNumPy/blob/master/include/itkPyBuffer.hxx) using the Python C-API.

**Comment by thewtex** [comment]
To confirm, ITK still supports compilers without C++11 support (VS2008 and GCC4.2).
